### ISSUE TITLE
Graphs and forecasts are not displayed anymore since HA 2024.4.1

### ISSUE THREAD

**Issue by smalinj** [mawinkler/astroweather-card#18] opened 2024-04-07 14:07 UTC
Hi,

Graphs and forecasts are not displayed anymore since HA 2024.4.1

For simple configuration as the two below we miss all forecasts or graphs information.

![Screenshot 2024-04-07 16 04 09](https://github.com/mawinkler/astroweather-card/assets/11733598/6117a8a6-b5cd-424e-a48c-f2b582c85ff0)
![Screenshot 2024-04-07 16 03 04](https://github.com/mawinkler/astroweather-card/assets/11733598/03ff0aaf-057f-4e48-99bb-b8121276b848)

Not sure how to fix it. Thank you for your support.

**Comment by mawinkler** [comment] 2024-04-08 06:14
Confirmed. It looks like I finally need use `getForecast` in the card. The AstroWeather integration already does support that but until now I haven't figured out how to access this service from the `.js` card. Any help would be appreciated!
Until then, the forecast is not working on HA 2024.4.1, I have to admit.

**Comment by mawinkler** [comment] 2024-04-11 17:50
I just pushed an updated version of the card, so please redownload from main.

No new release yet since there is somewhere a little bug creating an error on the javascript console. Besides that, it should now work again.
I will create a new release when I have found the glitch.

<img width="510" alt="image" src="https://github.com/mawinkler/astroweather-card/assets/16704258/33b3247e-c012-4841-9a30-69436beedd57">

**Comment by smalinj** [comment] 2024-04-11 19:09
Confirmed to be working again on my side.

**Comment by mawinkler** [comment] 2024-04-12 04:49
Thank you.
Fixed with [v0.42.2](https://github.com/mawinkler/astroweather-card/releases/tag/v0.42.2).

**Closed by mawinkler** 2024-04-12 04:49 UTC
